package me.c10coding.CustomEnchants.utils;

public enum EnchantmentKeys {
	life_steal,
	auto_repair,
	deep_wounds,
	headless,
	tempest,
	swift_foot,
	chest_implants,
	crippling_shot,
	shuffle_shot,
	wither_blow,
	wither_shot,
	piercing,
	molten,
	enlightening,
	muscle_sap,
	frozen_touch,
	music_to_ears,
	undying_surge,
	berserker,
	night_vision,
	fast_learning,
	shard_harvesting,
	vandalorian_accelerator,
	health_booster, extra_life, advanced_Bow,
}
