Enchants:
  Life_Steal:
    ChancePerLevel:
      1: 20
      2: 40
      3: 60
  Deep_Wounds:
    ChancePerLevel:
      1: 10
      2: 20
      3: 30
      4: 35
      5: 40
    PercentageDamageToBleeding: 0.25
    LengthBleeding: 10
  Headless:
    ChancePerLevel:
      1: 50
      2: 70
      3: 100
  Tempest:
    StrikesPerLevel:
      1: 1
      2: 2
    PercentageLightningDmgIncrease: 0.10
  Swift_Foot:
    PercantageIncreasePerLevel:
      1: .10
      2: .20
      3: .30
      4: .40
      5: .50
  Crippling_Shot:
    SlownessLength: 2.5
  Shuffle_Shot:
    CooldownPerLevel:
      1: 30
      2: 20
      3: 10
  Wither_Blow:
    ChancePerLevel:
      1: 10
      2: 25
      3: 40
    WitherLength: 6
  Wither_Shot:
    ChancePerLevel:
      1: 25
      2: 35
      3: 45
    WitherLength: 6
  Piercing:
    ChancePerLevel:
      1: 15
      2: 30
      3: 50
  Enlightening:
    ChancePerLevel:
      1: 10
      2: 13
      3: 15
  Molten:
    ChancePerLevel:
      1: 10
      2: 12
    LengthFire: 7
  Muscle_Sap:
    DecreasePercentagePerLevel:
      1: 20
      2: 40
      3: 50
    CooldownPerLevel:
      1: 30
      2: 25
      3: 25
  Frozen_Touch:
    DecreasedPercentagePerLevel:
      1: 10
      2: 13
      3: 15
    LengthPerLevel:
      1: 5
      2: 8
      3: 8
    ChancePerLevel:
      1: 10
      2: 15
      3: 18